apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service
spec:
  selector:
    matchLabels:
      app: category-service
  replicas: 1
  template:
    metadata:
      labels:
        app: category-service
    spec:
      containers:
        - name: category-service
          image: category-service:latest
          envFrom:
            - configMapRef:
                name: category-service
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: category-service
  labels:
    app: category-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: category-service
